/**
 * GameConfig — zentrale Balance-Werte.
 * Modular: jede Balance-Änderung nur hier.
 */
export const GameConfig = Object.freeze({
    version: '0.11.0',
    saveKey: 'idle_hacker_tycoon_v02',
    // Version des Save-Schemas (unabhängig vom localStorage-Key).
    // Bei Schema-Änderungen: hier erhöhen + Migration in Game.MIGRATIONS ergänzen.
    schemaVersion: 1,
    saveIntervalMs: 5000,
    offlineCapHours: 12,
    // Ab wie vielen Sekunden Tab-Abwesenheit Catch-Up-Ertrag gewährt wird
    offlineCatchUpMinSec: 10,
    tickRate: 10, // Ticks pro Sekunde für passive Income

    startingBits: 0,
    baseClickValue: 1,

    prestige: {
        // Ab 1M totalEarned kann prestiget werden (Basiswert bei totalPrestiges=0)
        threshold: 1_000_000,
        // Schwelle wächst pro Prestige: threshold * thresholdGrowth^totalPrestiges,
        // sonst wäre sie mit wachsenden permanenten Boni in Sekunden erreichbar.
        thresholdGrowth: 1.3,
        // 1 Punkt pro 1M (aufgerundet via gainDivisor) — bleibt fix, Gain wächst
        // automatisch mit, weil eine höhere Schwelle mehr totalEarned verlangt.
        gainDivisor: 1_000_000,
        // +10% global auf Klick + Generatoren pro Punkt
        multiplierPerPoint: 0.05,
        // Meilenstein-Boni: ab N Gesamt-Prestiges permanent aktiv
        // effect.type: 'start_bits' (Bits nach Reset) | 'global_mult' (Multiplikator)
        milestones: [
            { prestiges: 1, icon: '🌱', name: 'Wiedergeboren', description: 'Nach jedem Root-Zugriff startest du mit 500 Bits.', effect: { type: 'start_bits', value: 500 } },
            { prestiges: 3, icon: '🛡️', name: 'Netz-Veteran', description: 'Start mit 25.000 Bits nach jedem Root-Zugriff.', effect: { type: 'start_bits', value: 25_000 } },
            { prestiges: 5, icon: '👑', name: 'Legende des Netzes', description: '×2 auf Klick & alle Server — permanent.', effect: { type: 'global_mult', value: 2 } },
            { prestiges: 10, icon: '🕵️', name: 'Schatten-Legion', description: 'Start mit 50.000 Bits nach jedem Root-Zugriff.', effect: { type: 'start_bits', value: 50_000 } },
            { prestiges: 15, icon: '⚙️', name: 'System-Architekt', description: '×1.15 auf Klick & alle Server — permanent.', effect: { type: 'global_mult', value: 1.15 } },
            { prestiges: 20, icon: '🧿', name: 'Unsichtbarer Admin', description: 'Start mit 150.000 Bits nach jedem Root-Zugriff.', effect: { type: 'start_bits', value: 150_000 } },
            { prestiges: 25, icon: '🛠️', name: 'Root-Baumeister', description: '×1.15 auf Klick & alle Server — permanent.', effect: { type: 'global_mult', value: 1.15 } },
            { prestiges: 30, icon: '🌐', name: 'Netzwerk-Souverän', description: 'Start mit 400.000 Bits nach jedem Root-Zugriff.', effect: { type: 'start_bits', value: 400_000 } },
            { prestiges: 35, icon: '🚀', name: 'Exabyte-Architekt', description: '×1.2 auf Klick & alle Server — permanent.', effect: { type: 'global_mult', value: 1.2 } },
            { prestiges: 40, icon: '🧬', name: 'Digitale Gottheit', description: 'Start mit 1.000.000 Bits nach jedem Root-Zugriff.', effect: { type: 'start_bits', value: 1_000_000 } },
            { prestiges: 45, icon: '🕳️', name: 'Void-Operator', description: '×1.2 auf Klick & alle Server — permanent.', effect: { type: 'global_mult', value: 1.2 } },
            { prestiges: 50, icon: '👁️', name: 'Allsehendes Auge', description: '×1.3 auf Klick & alle Server — permanent.', effect: { type: 'global_mult', value: 1.3 } },
        ],
    },

    // Kategorien für gruppierte Darstellung (Tier-A = Einstieg … Tier-D = Endgame)
    generatorCategories: [
        { id: 'tier1', name: 'Einstieg', icon: '🌱', desc: '15–1,1k · schneller ROI' },
        { id: 'tier2', name: 'Mittelklasse', icon: '⚙️', desc: '4k–130k · stabiler Ertrag' },
        { id: 'tier3', name: 'Hochleistung', icon: '🚀', desc: '500k–20M · skaliert stark' },
        { id: 'tier4', name: 'Endgame', icon: '🌌', desc: '85M–6B · nur mit Prestige' },
    ],

    generators: [
        {
            id: 'script_kiddie',
            name: 'Script Kiddie',
            icon: '💻',
            description: 'Führt fertige Exploits aus',
            baseCost: 15,
            costMultiplier: 1.15,
            basePerSec: 0.5,
            category: 'tier1',
        },
        {
            id: 'proxy_chain',
            name: 'Proxy-Kette',
            icon: '🧦',
            description: 'Verschleiert deine Spur durch Ketten von Proxies',
            baseCost: 45,
            costMultiplier: 1.14,
            basePerSec: 1.2,
            category: 'tier1',
        },
        {
            id: 'botnet',
            name: 'Botnet',
            icon: '🤖',
            description: 'Netz aus Zombie-PCs',
            baseCost: 100,
            costMultiplier: 1.14,
            basePerSec: 4,
            category: 'tier1',
        },
        {
            id: 'crypto_miner',
            name: 'Krypto-Miner',
            icon: '🪙',
            description: 'Schürft nebenbei Kryptowährung',
            baseCost: 350,
            costMultiplier: 1.14,
            basePerSec: 12,
            category: 'tier1',
        },
        {
            id: 'server_farm',
            name: 'Server Farm',
            icon: '🖥️',
            description: 'Eigene Mining & Cracking Farm',
            baseCost: 1100,
            costMultiplier: 1.13,
            basePerSec: 30,
            category: 'tier1',
        },
        {
            id: 'ddos_rig',
            name: 'DDoS-Rig',
            icon: '⚡',
            description: 'Mietbare Angriffs-Infrastruktur',
            baseCost: 4000,
            costMultiplier: 1.14,
            basePerSec: 90,
            category: 'tier2',
        },
        {
            id: 'quantum_rig',
            name: 'Quantum Rig',
            icon: '⚛️',
            description: 'Bricht Verschlüsselung in Sekunden',
            baseCost: 12000,
            costMultiplier: 1.14,
            basePerSec: 220,
            category: 'tier2',
        },
        {
            id: 'zero_day_lab',
            name: 'Zero-Day-Labor',
            icon: '🧪',
            description: 'Entwickelt exklusive Zero-Day-Exploits',
            baseCost: 45000,
            costMultiplier: 1.15,
            basePerSec: 650,
            category: 'tier2',
        },
        {
            id: 'ai_swarm',
            name: 'KI-Schwarm',
            icon: '🧠',
            description: 'Autonome Hacker-KI',
            baseCost: 130000,
            costMultiplier: 1.15,
            basePerSec: 1600,
            category: 'tier2',
        },
        {
            id: 'deepfake_studio',
            name: 'Deepfake-Studio',
            icon: '🎭',
            description: 'Automatisierte Social-Engineering-Kampagnen',
            baseCost: 500000,
            costMultiplier: 1.15,
            basePerSec: 4800,
            category: 'tier3',
        },
        {
            id: 'dark_market',
            name: 'Darknet-Markt',
            icon: '🕸️',
            description: 'Waffenhandel & Datenauctionen',
            baseCost: 1500000,
            costMultiplier: 1.15,
            basePerSec: 12000,
            category: 'tier3',
        },
        {
            id: 'exchange_heist',
            name: 'Börsen-Coup',
            icon: '🏦',
            description: 'Unterwandert Börsen-Infrastruktur',
            baseCost: 6500000,
            costMultiplier: 1.14,
            basePerSec: 42000,
            category: 'tier3',
        },
        {
            id: 'satellite_uplink',
            name: 'Satelliten-Uplink',
            icon: '🛰️',
            description: 'Orbitale Abhör-Infrastruktur',
            baseCost: 20000000,
            costMultiplier: 1.14,
            basePerSec: 95000,
            category: 'tier3',
        },
        {
            id: 'quantum_datacenter',
            name: 'Quanten-Rechenzentrum',
            icon: '🏢',
            description: 'Verteiltes Quanten-Rechenzentrum',
            baseCost: 85000000,
            costMultiplier: 1.15,
            basePerSec: 340000,
            category: 'tier4',
        },
        {
            id: 'neural_overmind',
            name: 'Neural Overmind',
            icon: '🌌',
            description: 'Verteiltes Super-Wesen aus gestohlenen Gehirnen',
            baseCost: 300000000,
            costMultiplier: 1.15,
            basePerSec: 900000,
            category: 'tier4',
        },
        {
            id: 'dyson_botnet',
            name: 'Dyson-Botnetz',
            icon: '🌞',
            description: 'Sammelt Sonnenenergie für globale Botnetze',
            baseCost: 1300000000,
            costMultiplier: 1.15,
            basePerSec: 3200000,
            category: 'tier4',
        },
        {
            id: 'singularity_core',
            name: 'Singularitäts-Kern',
            icon: '♾️',
            description: 'Post-menschliche Rechenleistung ohne Grenzen',
            baseCost: 6000000000,
            costMultiplier: 1.16,
            basePerSec: 14000000,
            category: 'tier4',
        },
    ],

    // Kategorien für Upgrade-Tab (4 Gruppen)
    upgradeCategories: [
        { id: 'click', name: 'Klick', icon: '👆', desc: 'HACK selbst verstärken' },
        { id: 'server', name: 'Server-Boosts', icon: '⚙️', desc: 'einzelne Generator-Typen' },
        { id: 'global', name: 'Global', icon: '🌋', desc: 'alle Server gleichzeitig' },
        { id: 'utility', name: 'Effizienz', icon: '🛠️', desc: 'Kosten & Offline' },
    ],

    upgrades: [
        {
            id: 'better_keyboard',
            name: 'Mechanische Tastatur',
            icon: '⌨️',
            description: 'Doppelte Klick-Power',
            cost: 50,
            effect: { type: 'click_mult', value: 2 },
            requires: null,
            category: 'click',
        },
        {
            id: 'energy_drink',
            name: 'Energy Drink IV',
            icon: '🥤',
            description: 'Nochmals +100% pro Klick',
            cost: 500,
            effect: { type: 'click_mult', value: 2 },
            requires: 'better_keyboard',
            category: 'click',
        },
        {
            id: 'script_optimization',
            name: 'Script Optimierung',
            icon: '⚡',
            description: 'Script Kiddies +75% Output',
            cost: 300,
            effect: { type: 'generator_mult', target: 'script_kiddie', value: 1.75 },
            requires: null,
            category: 'server',
        },
        {
            id: 'botnet_upgrade',
            name: 'Botnet 2.0',
            icon: '🛰️',
            description: 'Botnets +100% Output',
            cost: 2500,
            effect: { type: 'generator_mult', target: 'botnet', value: 2 },
            requires: null,
            category: 'server',
        },
        {
            id: 'overclock',
            name: 'Übertaktung',
            icon: '🔥',
            description: 'Alle Server +50%',
            cost: 15000,
            effect: { type: 'global_mult', value: 1.5 },
            requires: null,
            category: 'global',
        },
        {
            id: 'quantum_cooling',
            name: 'Quantum Cooling',
            icon: '❄️',
            description: 'Quantum Rigs ×2 Output',
            cost: 80000,
            effect: { type: 'generator_mult', target: 'quantum_rig', value: 2 },
            requires: null,
            category: 'server',
        },
        {
            id: 'bionic_fingers',
            name: 'Bionische Finger',
            icon: '🦾',
            description: 'Klick-Power ×3',
            cost: 100000,
            effect: { type: 'click_mult', value: 3 },
            requires: 'energy_drink',
            category: 'click',
        },
        {
            id: 'swarm_protocol',
            name: 'Schwarm-Protokoll',
            icon: '🧬',
            description: 'KI-Schwärme +150% Output',
            cost: 600000,
            effect: { type: 'generator_mult', target: 'ai_swarm', value: 2.5 },
            requires: null,
            category: 'server',
        },
        {
            id: 'overclock_ii',
            name: 'Übertaktung II',
            icon: '🌋',
            description: 'Alle Server +100%',
            cost: 2500000,
            effect: { type: 'global_mult', value: 2 },
            requires: 'overclock',
            category: 'global',
        },
        {
            id: 'market_bot',
            name: 'Markt-Bot',
            icon: '🕶️',
            description: 'Darknet-Märkte +150% Output',
            cost: 4000000,
            effect: { type: 'generator_mult', target: 'dark_market', value: 2.5 },
            requires: null,
            category: 'server',
        },
        {
            id: 'uplink_turbo',
            name: 'Uplink-Turbo',
            icon: '📡',
            description: 'Satelliten-Uplinks +150% Output',
            cost: 40000000,
            effect: { type: 'generator_mult', target: 'satellite_uplink', value: 2.5 },
            requires: null,
            category: 'server',
        },
        {
            id: 'server_virtualization',
            name: 'Server-Virtualisierung',
            icon: '📦',
            description: 'Server Farms +100% Output',
            cost: 500000,
            effect: { type: 'generator_mult', target: 'server_farm', value: 2 },
            requires: null,
            category: 'server',
        },
        {
            id: 'neural_link',
            name: 'Neural-Link',
            icon: '🔗',
            description: 'Neural Overminds +200% Output',
            cost: 500000000,
            effect: { type: 'generator_mult', target: 'neural_overmind', value: 3 },
            requires: null,
            category: 'server',
        },
        {
            id: 'overclock_iii',
            name: 'Übertaktung III',
            icon: '☄️',
            description: 'Alle Server +200%',
            cost: 100000000,
            effect: { type: 'global_mult', value: 3 },
            requires: 'overclock_ii',
            category: 'global',
        },
        {
            id: 'caffeine_iv',
            name: 'Koffein-Infusion',
            icon: '☕',
            description: 'Klick-Power ×5',
            cost: 10000000,
            effect: { type: 'click_mult', value: 5 },
            requires: 'bionic_fingers',
            category: 'click',
        },
        {
            id: 'cost_optimizer',
            name: 'Kosten-Optimierer',
            icon: '💰',
            description: 'Alle Generatoren 10% günstiger (Cost-Mult ×0.95)',
            cost: 25000000,
            effect: { type: 'cost_reduction', value: 0.95 },
            requires: 'overclock',
            category: 'utility',
        },
        {
            id: 'offline_extender',
            name: 'Offline-Extender',
            icon: '🌙',
            description: 'Offline-Cap auf 24h verdoppeln',
            cost: 5000000,
            effect: { type: 'offline_cap_mult', value: 2 },
            requires: null,
            category: 'utility',
        },
        {
            id: 'proxy_upgrade',
            name: 'Proxy-Ketten 2.0',
            icon: '🧦',
            description: 'Proxy-Ketten +100% Output',
            cost: 900,
            effect: { type: 'generator_mult', target: 'proxy_chain', value: 2 },
            requires: null,
            category: 'server',
        },
        {
            id: 'mining_pool',
            name: 'Mining-Pool',
            icon: '🪙',
            description: 'Krypto-Miner +100% Output',
            cost: 7000,
            effect: { type: 'generator_mult', target: 'crypto_miner', value: 2 },
            requires: null,
            category: 'server',
        },
        {
            id: 'ddos_amplification',
            name: 'DDoS-Verstärkung',
            icon: '⚡',
            description: 'DDoS-Rigs +100% Output',
            cost: 80000,
            effect: { type: 'generator_mult', target: 'ddos_rig', value: 2 },
            requires: null,
            category: 'server',
        },
        {
            id: 'exploit_database',
            name: 'Exploit-Datenbank',
            icon: '🧪',
            description: 'Zero-Day-Labore +150% Output',
            cost: 900000,
            effect: { type: 'generator_mult', target: 'zero_day_lab', value: 2.5 },
            requires: null,
            category: 'server',
        },
        {
            id: 'synthetic_voices',
            name: 'Synthetische Stimmen',
            icon: '🎭',
            description: 'Deepfake-Studios +150% Output',
            cost: 10000000,
            effect: { type: 'generator_mult', target: 'deepfake_studio', value: 2.5 },
            requires: null,
            category: 'server',
        },
        {
            id: 'insider_access',
            name: 'Insider-Zugang',
            icon: '🏦',
            description: 'Börsen-Coups +150% Output',
            cost: 130000000,
            effect: { type: 'generator_mult', target: 'exchange_heist', value: 2.5 },
            requires: null,
            category: 'server',
        },
        {
            id: 'qubit_array',
            name: 'Qubit-Array',
            icon: '🏢',
            description: 'Quanten-Rechenzentren +200% Output',
            cost: 1700000000,
            effect: { type: 'generator_mult', target: 'quantum_datacenter', value: 3 },
            requires: null,
            category: 'server',
        },
        {
            id: 'solar_collector',
            name: 'Solar-Kollektor',
            icon: '🌞',
            description: 'Dyson-Botnetze +200% Output',
            cost: 26000000000,
            effect: { type: 'generator_mult', target: 'dyson_botnet', value: 3 },
            requires: null,
            category: 'server',
        },
        {
            id: 'singularity_matrix',
            name: 'Singularitäts-Matrix',
            icon: '♾️',
            description: 'Singularitäts-Kerne +200% Output',
            cost: 120000000000,
            effect: { type: 'generator_mult', target: 'singularity_core', value: 3 },
            requires: null,
            category: 'server',
        },
        {
            id: 'overclock_iv',
            name: 'Übertaktung IV',
            icon: '🌠',
            description: 'Alle Server +100%',
            cost: 2000000000,
            effect: { type: 'global_mult', value: 2 },
            requires: 'overclock_iii',
            category: 'global',
        },
        {
            id: 'overclock_v',
            name: 'Übertaktung V',
            icon: '🪐',
            description: 'Alle Server +150%',
            cost: 20000000000,
            effect: { type: 'global_mult', value: 2.5 },
            requires: 'overclock_iv',
            category: 'global',
        }
    ],

    prestigeShop: [
        { id: 'sp_global', name: 'Root-Protokoll', icon: '🔑', description: '+5% auf alle Server pro Stufe', baseCost: 2, costMultiplier: 1.6, maxLevel: 30, effect: { type: 'global_mult_add', perLevel: 0.05 } },
        { id: 'sp_click', name: 'Neuronale Beschleunigung', icon: '🧠', description: '+10% Klick-Power pro Stufe', baseCost: 1, costMultiplier: 1.5, maxLevel: 20, effect: { type: 'click_mult_add', perLevel: 0.10 } },
        { id: 'sp_gain', name: 'Effiziente Extraktion', icon: '📈', description: '+10% Root-Keys & CPU-Chips pro Prestige, pro Stufe', baseCost: 5, costMultiplier: 1.8, maxLevel: 15, effect: { type: 'prestige_gain_mult', perLevel: 0.10 } },
        { id: 'sp_start', name: 'Notfall-Fonds', icon: '💼', description: '+50.000 Start-Bits nach Reset, pro Stufe', baseCost: 3, costMultiplier: 2.0, maxLevel: 10, effect: { type: 'start_bits_add', perLevel: 50000 } },
        { id: 'sp_offline', name: 'Autonomie-Kern', icon: '🌙', description: '+25% Offline-Cap pro Stufe', baseCost: 4, costMultiplier: 1.7, maxLevel: 8, effect: { type: 'offline_cap_add', perLevel: 0.25 } },
        { id: 'sp_cost', name: 'Schwarzmarkt-Kontakte', icon: '💰', description: 'Generator-Kosten -2% pro Stufe (max. -50%)', baseCost: 6, costMultiplier: 2.0, maxLevel: 10, effect: { type: 'cost_reduction_add', perLevel: 0.02 } },
    ],

    levelThresholds: [0, 100, 1000, 10000, 100000, 1000000, 10000000, 100000000, 1000000000],
    levelNames: ['Script Kiddie', 'Junior Hacker', 'Hacker', 'Elite Hacker', 'Cyber Ghost', 'Root God', 'Netz-Baron', 'Daten-Kaiser', 'Singularity'],

    getGenerator(id) {
        return this.generators.find(g => g.id === id) ?? null;
    },
    getUpgrade(id) {
        return this.upgrades.find(u => u.id === id) ?? null;
    },
    getPrestigeShopItem(id) {
        return this.prestigeShop.find(i => i.id === id) ?? null;
    },
});
